### ISSUE TITLE
Build 0.0.28 on demo page doesn't recognize any SWFs as SWFs

### ISSUE THREAD

**Issue by sfmemz** [eXponenta/away-player-embed#1]

**Comment by eXponenta** [comment]
This is strange.
For mw all ok on PC (Chrome and FF), on Android and iPad.

SWZ (apps greater that Flash 11.4) not supported now

**Comment by sfmemz** [comment]
[cut_the_rope_experiments.zip](https://github.com/eXponenta/away-player-embed/files/6795335/cut_the_rope_experiments.zip)
It used to work on 0.0.27

**Comment by eXponenta** [comment]
It shouldn't working with this namings:
![image](https://user-images.githubusercontent.com/12572222/125165454-a3421a00-e19f-11eb-8666-2225fe4661aa.png)

JIT translator emit JS code that not like obfiscated source. Use plain SWF and all will be ok.

**Comment by sfmemz** [comment]
I mean all the SWF I've tested on the tester had this issue, the embed is unaffected.

**Comment by eXponenta** [comment]
> I mean all the SWF I've tested on the tester had this issue, the embed is unaffected.

Runtime is develops is game specific.
This is because flash has huge API that need implement, we can't create a runtime that will working for all possible games from scratch.

We have pool of games that  has high priority and try to run this games because investors paid for those games.

**Comment by sfmemz** [comment]
the tester can now recognize swfs, case closed
